#!/system/bin/sh
# Long-lived native runner. Persistent credentials/config deliberately live outside
# the module directory so an in-place Magisk module update cannot overwrite them.
MODDIR=$1
BASE=/data/adb/workbuddy2api
BIN="$MODDIR/bin/wb2api"
LOG="$BASE/log/wb2api.log"
PIDFILE="$BASE/wb2api.pid"
SUPERVISOR_PID="$BASE/runner.pid"

umask 077
mkdir -p "$BASE/auths" "$BASE/data" "$BASE/log"
chmod 700 "$BASE" "$BASE/auths" "$BASE/data" "$BASE/log"

# Late-start is normally after boot. Waiting briefly prevents a first-start race
# with /data and Android network services, without holding a wake lock afterwards.
i=0
while [ "$(getprop sys.boot_completed)" != "1" ] && [ "$i" -lt 90 ]; do
  sleep 2
  i=$((i + 1))
done

# --- DNS ---
# The binary is CGO_ENABLED=0, so it uses Go's pure resolver, which only reads
# /etc/resolv.conf (or /system/etc/resolv.conf). Android has neither: netd gives
# each process its DNS servers via the network stack, not a file. Without the file
# the resolver falls back to [::1]:53, every lookup fails with "connection refused",
# and /v1/models returns an empty list (chat cannot reach the upstream either).
#
# /etc is a symlink to /system/etc, and /system is a read-only erofs, so the file
# cannot be written or bind-mounted at runtime. The only reliable path is Magisk's
# own overlay: $MODDIR/system/etc/resolv.conf is mirrored onto /system/etc at boot.
# We therefore (a) generate the file, (b) install it into the module overlay, and
# (c) still try a runtime bind mount so a service restart without reboot also works
# on ROMs where the mount succeeds.
DNSFILE="$BASE/resolv.conf"
OVERLAY_DIR="$MODDIR/system/etc"

collect_dns() {
  # 1) legacy props (some ROMs still publish them)
  for k in net.dns1 net.dns2 net.dns3 net.dns4; do
    v=$(getprop "$k" 2>/dev/null)
    case "$v" in ''|0.0.0.0|::) ;; *) echo "$v";; esac
  done
  # 2) DNS of every currently attached network (Wi-Fi / VPN / cellular)
  dumpsys connectivity 2>/dev/null | sed -n 's/.*DnsAddresses: \[ \([^]]*\)\].*/\1/p' \
    | tr ',' '\n' | sed -n 's|/||p'
}

{
  echo "# generated by workbuddy2api Magisk module at $(date '+%Y-%m-%d %H:%M:%S')"
  collect_dns | awk 'NF && !seen[$0]++ { print "nameserver " $0 }' | head -4
} > "$DNSFILE" 2>/dev/null

# Public-resolver fallback: keeps the gateway usable on ROMs that expose no DNS
# information to non-system processes. Reachability of these two was verified on a
# CN network; they are only used when nothing was discovered above.
if [ "$(grep -c '^nameserver' "$DNSFILE" 2>/dev/null)" -eq 0 ] 2>/dev/null; then
  printf 'nameserver %s\n' 223.5.5.5 119.29.29.29 114.114.114.114 >> "$DNSFILE"
fi
chmod 644 "$DNSFILE" 2>/dev/null

# (b) module overlay: takes effect on the next boot.
if mkdir -p "$OVERLAY_DIR" 2>/dev/null; then
  cp -f "$DNSFILE" "$OVERLAY_DIR/resolv.conf" 2>/dev/null && chmod 644 "$OVERLAY_DIR/resolv.conf" 2>/dev/null
fi

# (c) runtime bind mount: helps when the operator restarts the service without a
# reboot and the target happens to be writable. Failure is expected and harmless.
for target in /system/etc/resolv.conf /etc/resolv.conf; do
  mount -o bind "$DNSFILE" "$target" 2>/dev/null \
    || mount --bind "$DNSFILE" "$target" 2>/dev/null || true
done

printf '%s runner: dns [%s] overlay=%s\n' "$(date '+%Y-%m-%d %H:%M:%S')" \
  "$(grep '^nameserver' "$DNSFILE" 2>/dev/null | awk '{print $2}' | tr '\n' ',')" \
  "$([ -f "$OVERLAY_DIR/resolv.conf" ] && echo yes || echo no)" >> "$LOG" 2>/dev/null

# Do not run two copies if service.sh is accidentally invoked more than once.
if [ -r "$SUPERVISOR_PID" ]; then
  old=$(cat "$SUPERVISOR_PID" 2>/dev/null)
  if [ -n "$old" ] && kill -0 "$old" 2>/dev/null; then
    exit 0
  fi
fi
printf '%s\n' "$$" > "$SUPERVISOR_PID"
trap 'rm -f "$PIDFILE" "$SUPERVISOR_PID"; exit 0' INT TERM EXIT

# This is deliberately a normal idle TCP server: no foreground notification,
# wakelock, alarm loop, or polling watchdog. The Go scheduler performs the
# existing check-in, activity, travel, keepalive, blackcat, and balance jobs.
export WB2A_ANDROID_MODULE=1
export WB2A_AUTH_DIR="$BASE/auths"
export WB2A_STATE_FILE="$BASE/data/state.json"
export TZ=Asia/Shanghai

backoff=5
while [ -x "$BIN" ]; do
  # Tiny rotation only at process boundaries; request logs are otherwise stdout/stderr.
  if [ -f "$LOG" ]; then
    size=$(wc -c < "$LOG" 2>/dev/null)
    if [ "${size:-0}" -gt 2097152 ]; then
      mv -f "$LOG" "$LOG.1" 2>/dev/null
    fi
  fi
  printf '%s runner: starting wb2api\n' "$(date '+%Y-%m-%d %H:%M:%S')" >> "$LOG"
  "$BIN" -config "$BASE/config.json" >> "$LOG" 2>&1 &
  child=$!
  printf '%s\n' "$child" > "$PIDFILE"
  wait "$child"
  code=$?
  rm -f "$PIDFILE"
  printf '%s runner: wb2api exited code=%s; retry in %ss\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$code" "$backoff" >> "$LOG"
  sleep "$backoff"
  [ "$backoff" -lt 60 ] && backoff=$((backoff * 2))
done
